[platformio]
default_envs = esp32s3

; ESP-FC's lib/ directory is a PlatformIO library storage.
; Drone Pet consumes those libraries; it does not consume ESP-FC's app/main.cpp.
lib_dir = ../esp-fc/lib


[env:esp32s3]
platform = espressif32
board = lolin_s3_mini
framework = arduino

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = ../esp-fc/partitions_4M_nota.csv

build_unflags =
    -std=gnu++11
    -ggdb
    -DBOARD_HAS_PSRAM

build_flags =
    -std=gnu++17
    -Wall
    -DESP32S3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
monitor_filters = send_on_enter
monitor_echo = yes

upload_speed = 921600

board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes

lib_deps =
    yoursunny/WifiEspNow @ ^0.0.20230713
    https://github.com/rtlopez/espnow-rclink/archive/refs/tags/v0.1.1.zip